# Generated by Django 5.2.13 on 2026-04-23 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="カテゴリ名"
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        max_length=120, unique=True, verbose_name="スラッグ"
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="説明")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "カテゴリ",
                "verbose_name_plural": "カテゴリ",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="商品名")),
                (
                    "slug",
                    models.SlugField(
                        allow_unicode=True,
                        max_length=220,
                        unique=True,
                        verbose_name="スラッグ",
                    ),
                ),
                (
                    "brand",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="メーカー"
                    ),
                ),
                (
                    "price",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="参考価格(円)"
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="products/",
                        verbose_name="画像",
                    ),
                ),
                (
                    "image_url",
                    models.URLField(blank=True, verbose_name="画像URL(外部)"),
                ),
                ("description", models.TextField(blank=True, verbose_name="商品説明")),
                (
                    "features",
                    models.TextField(
                        blank=True, help_text="箇条書きで記載", verbose_name="特徴"
                    ),
                ),
                (
                    "official_url",
                    models.URLField(blank=True, verbose_name="公式サイトURL"),
                ),
                (
                    "affiliate_url",
                    models.URLField(blank=True, verbose_name="アフィリエイトURL"),
                ),
                (
                    "is_published",
                    models.BooleanField(default=True, verbose_name="公開"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "categories",
                    models.ManyToManyField(
                        blank=True,
                        related_name="products",
                        to="products.category",
                        verbose_name="カテゴリ",
                    ),
                ),
            ],
            options={
                "verbose_name": "美顔器",
                "verbose_name_plural": "美顔器",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="タイトル")),
                (
                    "slug",
                    models.SlugField(
                        allow_unicode=True,
                        max_length=280,
                        unique=True,
                        verbose_name="スラッグ",
                    ),
                ),
                ("content", models.TextField(verbose_name="本文(HTML)")),
                ("excerpt", models.TextField(blank=True, verbose_name="抜粋")),
                (
                    "wp_post_id",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        unique=True,
                        verbose_name="WordPress投稿ID",
                    ),
                ),
                (
                    "wp_author",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="WP投稿者"
                    ),
                ),
                (
                    "published_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="公開日"),
                ),
                (
                    "is_published",
                    models.BooleanField(default=True, verbose_name="公開"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "related_products",
                    models.ManyToManyField(
                        blank=True,
                        related_name="articles",
                        to="products.product",
                        verbose_name="関連商品",
                    ),
                ),
            ],
            options={
                "verbose_name": "記事",
                "verbose_name_plural": "記事",
                "ordering": ["-published_at", "-created_at"],
            },
        ),
    ]
