# Generated by Django 5.2.13 on 2026-04-23 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={
                "ordering": ["sort_order", "-created_at"],
                "verbose_name": "美顔器",
                "verbose_name_plural": "美顔器",
            },
        ),
        migrations.AddField(
            model_name="product",
            name="amazon_url",
            field=models.URLField(blank=True, verbose_name="AmazonURL"),
        ),
        migrations.AddField(
            model_name="product",
            name="rakuten_url",
            field=models.URLField(blank=True, verbose_name="楽天URL"),
        ),
        migrations.AddField(
            model_name="product",
            name="sort_order",
            field=models.IntegerField(db_index=True, default=0, verbose_name="表示順"),
        ),
        migrations.AddField(
            model_name="product",
            name="wp_post_id",
            field=models.IntegerField(
                blank=True, null=True, unique=True, verbose_name="WordPress投稿ID"
            ),
        ),
    ]
