# Generated by Django 5.2.13 on 2026-04-23 16:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_alter_product_options_product_amazon_url_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={
                "ordering": ["sort_order", "name"],
                "verbose_name": "カテゴリ",
                "verbose_name_plural": "カテゴリ",
            },
        ),
        migrations.AddField(
            model_name="category",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="children",
                to="products.category",
                verbose_name="親カテゴリ (製品タイプ)",
            ),
        ),
        migrations.AddField(
            model_name="category",
            name="sort_order",
            field=models.IntegerField(default=0, verbose_name="表示順"),
        ),
        migrations.AddField(
            model_name="product",
            name="product_type",
            field=models.ForeignKey(
                blank=True,
                help_text="美顔器、ドライヤー等の製品タイプ",
                limit_choices_to={"parent__isnull": True},
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="products_of_type",
                to="products.category",
                verbose_name="製品タイプ",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="categories",
            field=models.ManyToManyField(
                blank=True,
                related_name="products",
                to="products.category",
                verbose_name="機能カテゴリ",
            ),
        ),
    ]
