# Generated by Django 5.2.13 on 2026-04-23 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0003_alter_category_options_category_parent_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="slug",
            field=models.SlugField(
                allow_unicode=True, max_length=500, unique=True, verbose_name="スラッグ"
            ),
        ),
        migrations.AlterField(
            model_name="article",
            name="title",
            field=models.CharField(max_length=500, verbose_name="タイトル"),
        ),
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(
                max_length=200, unique=True, verbose_name="カテゴリ名"
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="slug",
            field=models.SlugField(
                allow_unicode=True, max_length=200, unique=True, verbose_name="スラッグ"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="brand",
            field=models.CharField(blank=True, max_length=200, verbose_name="メーカー"),
        ),
        migrations.AlterField(
            model_name="product",
            name="name",
            field=models.CharField(max_length=500, verbose_name="商品名"),
        ),
        migrations.AlterField(
            model_name="product",
            name="slug",
            field=models.SlugField(
                allow_unicode=True, max_length=500, unique=True, verbose_name="スラッグ"
            ),
        ),
    ]
