# Generated by Django 5.2.13 on 2026-04-23 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0004_alter_article_slug_alter_article_title_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="wp_author",
            field=models.CharField(blank=True, max_length=500, verbose_name="WP投稿者"),
        ),
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(
                max_length=500, unique=True, verbose_name="カテゴリ名"
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="slug",
            field=models.SlugField(
                allow_unicode=True, max_length=500, unique=True, verbose_name="スラッグ"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="brand",
            field=models.CharField(blank=True, max_length=500, verbose_name="メーカー"),
        ),
    ]
