# Generated by Django 5.2.13 on 2026-04-23 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0005_alter_article_wp_author_alter_category_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="affiliate_url",
            field=models.URLField(
                blank=True, max_length=1000, verbose_name="アフィリエイトURL"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="amazon_url",
            field=models.URLField(
                blank=True, max_length=1000, verbose_name="AmazonURL"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="image_url",
            field=models.URLField(
                blank=True, max_length=1000, verbose_name="画像URL(外部)"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="official_url",
            field=models.URLField(
                blank=True, max_length=1000, verbose_name="公式サイトURL"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="rakuten_url",
            field=models.URLField(blank=True, max_length=1000, verbose_name="楽天URL"),
        ),
    ]
