# Generated by Django 5.2.13 on 2026-04-26 10:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_product_affiliate_url_alter_product_amazon_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='product_type',
            field=models.ForeignKey(blank=True, limit_choices_to={'parent__isnull': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles_in_type', to='products.category', verbose_name='カテゴリ(製品タイプ)'),
        ),
    ]
