# Generated by Django 5.2.13 on 2026-04-26 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_article_product_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='landing_html',
            field=models.TextField(blank=True, help_text='カテゴリTOPのSEOランディングページのHTML本文。空ならデフォルト表示', verbose_name='ランディングHTML(SEO)'),
        ),
        migrations.AddField(
            model_name='category',
            name='meta_description',
            field=models.CharField(blank=True, max_length=300, verbose_name='SEOディスクリプション'),
        ),
        migrations.AddField(
            model_name='category',
            name='meta_title',
            field=models.CharField(blank=True, max_length=200, verbose_name='SEOタイトル'),
        ),
    ]
