# Generated by Django 5.2.13 on 2026-04-26 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_category_landing_html_category_meta_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='show_in_header',
            field=models.BooleanField(default=True, help_text='OFFにするとヘッダーのカテゴリナビから非表示になります', verbose_name='ヘッダーに表示'),
        ),
    ]
