# Generated by Django 5.2.13 on 2026-04-27 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_category_show_in_header'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='cautions',
            field=models.TextField(blank=True, help_text='使用時の注意点・禁忌事項。AI記事生成時に必ず含める内容', verbose_name='注意事項'),
        ),
        migrations.AddField(
            model_name='product',
            name='last_verified_at',
            field=models.DateField(blank=True, help_text='商品情報を公式から最終確認した日(古い情報での生成防止)', null=True, verbose_name='最終確認日'),
        ),
        migrations.AddField(
            model_name='product',
            name='specifications',
            field=models.JSONField(blank=True, default=dict, help_text='構造化スペック例: {"weight": "300g", "size": "100x50mm", "battery": "2400mAh"}', verbose_name='スペック'),
        ),
    ]
