# Generated by Django 5.2.13 on 2026-04-28 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_article_seo_check_result_article_seo_keyword'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='meta_description',
            field=models.CharField(blank=True, help_text='検索結果のスニペット(120-160文字推奨)。空欄なら抜粋が使われます。', max_length=200, verbose_name='SEOディスクリプション'),
        ),
        migrations.AddField(
            model_name='article',
            name='meta_title',
            field=models.CharField(blank=True, help_text='検索結果のタイトル(全角30文字程度推奨)。空欄ならタイトルが使われます。', max_length=100, verbose_name='SEOタイトル(<title>)'),
        ),
    ]
