# Generated by Django 5.2.13 on 2026-04-28 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_article_meta_description_article_meta_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='thumbnail',
            field=models.ImageField(blank=True, help_text='アップロード優先。空ならURL欄、それも空なら本文先頭の画像が使われます。', null=True, upload_to='articles/', verbose_name='アイキャッチ画像'),
        ),
        migrations.AddField(
            model_name='article',
            name='thumbnail_url',
            field=models.URLField(blank=True, help_text='外部URLを使う場合に入力。アップロード画像が優先されます。', max_length=500, verbose_name='アイキャッチ画像URL'),
        ),
    ]
