# Generated by Django 5.2.13 on 2026-04-28 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_article_thumbnail_article_thumbnail_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amazon_access_key', models.CharField(blank=True, max_length=100, verbose_name='Amazon Access Key')),
                ('amazon_secret_key', models.CharField(blank=True, max_length=200, verbose_name='Amazon Secret Key')),
                ('amazon_partner_tag', models.CharField(blank=True, help_text='Associates ID (例: mycafolio-22)', max_length=50, verbose_name='Amazon Partner Tag')),
                ('amazon_marketplace', models.CharField(default='www.amazon.co.jp', max_length=50, verbose_name='マーケットプレイス')),
                ('is_amazon_enabled', models.BooleanField(default=False, verbose_name='Amazon 連携を有効化')),
                ('rakuten_app_id', models.CharField(blank=True, max_length=100, verbose_name='楽天 アプリID')),
                ('rakuten_affiliate_id', models.CharField(blank=True, help_text='アフィリエイトリンクが自動付与されます', max_length=50, verbose_name='楽天 アフィリエイトID')),
                ('is_rakuten_enabled', models.BooleanField(default=False, verbose_name='楽天 連携を有効化')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'API 認証情報',
                'verbose_name_plural': 'API 認証情報',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='amazon_synced_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Amazon 同期日時'),
        ),
        migrations.AddField(
            model_name='product',
            name='api_data',
            field=models.JSONField(blank=True, default=dict, help_text='Amazon/楽天 APIレスポンス保管(画像複数・スペック等)', verbose_name='API 生データ'),
        ),
        migrations.AddField(
            model_name='product',
            name='asin',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True, verbose_name='Amazon ASIN'),
        ),
        migrations.AddField(
            model_name='product',
            name='rakuten_item_code',
            field=models.CharField(blank=True, db_index=True, max_length=100, verbose_name='楽天 itemCode'),
        ),
        migrations.AddField(
            model_name='product',
            name='rakuten_synced_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='楽天 同期日時'),
        ),
        migrations.AddField(
            model_name='product',
            name='source',
            field=models.CharField(choices=[('manual', '手動'), ('amazon', 'Amazon'), ('rakuten', '楽天'), ('wp', 'WP移行')], default='manual', max_length=20, verbose_name='登録経路'),
        ),
    ]
