# Generated by Django 5.2.13 on 2026-04-28 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_apicredential_product_amazon_synced_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='apicredential',
            name='rakuten_access_key',
            field=models.CharField(blank=True, help_text='新Open API用 (pk_xxx形式)', max_length=200, verbose_name='楽天 アクセスキー'),
        ),
    ]
