# Generated by Django 5.2.13 on 2026-04-28 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_apicredential_rakuten_access_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discontinued_at',
            field=models.DateField(blank=True, null=True, verbose_name='生産終了日'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_discontinued',
            field=models.BooleanField(default=False, help_text='チェックすると商品ページに「生産終了」表示+類似商品案内が出ます', verbose_name='生産終了'),
        ),
    ]
