# Generated by Django 5.2.13 on 2026-05-01 14:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_product_discontinued_at_product_is_discontinued'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='article-images/', verbose_name='画像')),
                ('alt_text', models.CharField(blank=True, max_length=200, verbose_name='代替テキスト(alt)')),
                ('caption', models.CharField(blank=True, max_length=200, verbose_name='キャプション')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='並び順')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.article', verbose_name='記事')),
            ],
            options={
                'verbose_name': '記事内画像',
                'verbose_name_plural': '記事内画像',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
