# Generated by Django 5.2.13 on 2026-05-03 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_articleimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='structured_data',
            field=models.TextField(blank=True, help_text='記事ページの head に script type="application/ld+json" として出力されます。FAQPage / ItemList / Article 等のスキーマを記述してください。', verbose_name='構造化データ(JSON-LD)'),
        ),
    ]
