# Generated by Django 5.2.13 on 2026-05-07 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_article_structured_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, help_text='カテゴリTOPに表示するイラスト・アイキャッチ画像', null=True, upload_to='categories/', verbose_name='カテゴリ画像(イラスト等)'),
        ),
        migrations.AddField(
            model_name='category',
            name='image_url',
            field=models.URLField(blank=True, help_text='外部URLで画像を指定する場合に使用(image欄が空のとき有効)', max_length=500, verbose_name='カテゴリ画像URL'),
        ),
    ]
