# Generated by Django 5.2.13 on 2026-05-07 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0019_category_image_category_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='meta_description',
            field=models.CharField(blank=True, help_text='検索結果のスニペット(120-160文字推奨)。空欄なら商品説明の冒頭が使われます。', max_length=200, verbose_name='SEOディスクリプション'),
        ),
        migrations.AddField(
            model_name='product',
            name='meta_title',
            field=models.CharField(blank=True, help_text='検索結果のタイトル(全角30文字程度推奨)。空欄なら商品名が使われます。', max_length=100, verbose_name='SEOタイトル(<title>)'),
        ),
    ]
