# Generated by Django 5.2.13 on 2026-05-21 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0020_product_meta_description_product_meta_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeoWeeklyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateField(verbose_name='期間開始')),
                ('period_end', models.DateField(verbose_name='期間終了')),
                ('generated_at', models.DateTimeField(auto_now_add=True, verbose_name='生成日時')),
                ('total_clicks', models.IntegerField(default=0, verbose_name='総クリック数')),
                ('total_impressions', models.IntegerField(default=0, verbose_name='総表示回数')),
                ('total_sessions', models.IntegerField(default=0, verbose_name='総セッション数')),
                ('avg_ctr', models.FloatField(default=0.0, verbose_name='平均CTR(%)')),
                ('avg_position', models.FloatField(default=0.0, verbose_name='平均掲載順位')),
                ('clicks_change_pct', models.FloatField(default=0.0, verbose_name='クリック前週比(%)')),
                ('sessions_change_pct', models.FloatField(default=0.0, verbose_name='セッション前週比(%)')),
                ('top_pages', models.JSONField(blank=True, default=list, verbose_name='上位ページ')),
                ('top_queries', models.JSONField(blank=True, default=list, verbose_name='上位クエリ')),
                ('winners', models.JSONField(blank=True, default=list, verbose_name='勝者ページ')),
                ('losers', models.JSONField(blank=True, default=list, verbose_name='順位低下ページ')),
                ('rewrite_candidates', models.JSONField(blank=True, default=list, verbose_name='リライト候補（順位11-20）')),
                ('ctr_underperformers', models.JSONField(blank=True, default=list, verbose_name='CTR弱者')),
                ('suggested_actions', models.JSONField(blank=True, default=list, verbose_name='アクション提案')),
                ('report_markdown', models.TextField(blank=True, verbose_name='レポート本文(Markdown)')),
            ],
            options={
                'verbose_name': '週次SEOレポート',
                'verbose_name_plural': '週次SEOレポート',
                'ordering': ['-period_end'],
            },
        ),
    ]
