# Generated by Django 5.2.13 on 2026-06-02 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0021_seoweeklyreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='index_checked_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='インデックス確認日時'),
        ),
        migrations.AddField(
            model_name='article',
            name='index_raw_status',
            field=models.TextField(blank=True, default='', help_text='URL Inspection API の coverageState 等を生で保持（デバッグ用）。', verbose_name='インデックスAPI生レスポンス'),
        ),
        migrations.AddField(
            model_name='article',
            name='index_status',
            field=models.CharField(blank=True, choices=[('', '未チェック'), ('indexed', '✅ Indexed'), ('crawled_not_indexed', '🔄 Crawled, not indexed'), ('discovered_not_indexed', '⏳ Discovered, not indexed'), ('excluded', '🚫 Excluded'), ('error', '⚠️ API error')], default='', help_text='URL Inspection API の coverageState から判定。check_indexing コマンドで更新。', max_length=64, verbose_name='Googleインデックス状況'),
        ),
    ]
