# Generated by Django 5.2.13 on 2026-06-04 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0022_article_index_checked_at_article_index_raw_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='related_articles',
            field=models.ManyToManyField(blank=True, help_text='商品ページ下部に表示する関連記事(機構hub/悩みhub/比較/選び方など最大4本)', related_name='related_products_reverse', to='products.article', verbose_name='関連記事'),
        ),
        migrations.AlterField(
            model_name='article',
            name='index_status',
            field=models.CharField(blank=True, choices=[('', '未チェック'), ('indexed', '✅ Indexed'), ('crawled_not_indexed', '🔄 Crawled, not indexed'), ('discovered_not_indexed', '⏳ Discovered, not indexed'), ('excluded', '🚫 Excluded'), ('unknown_to_google', '⏳ 未登録/未クロール'), ('error', '⚠️ API error')], default='', help_text='URL Inspection API の coverageState から判定。check_indexing コマンドで更新。', max_length=64, verbose_name='Googleインデックス状況'),
        ),
    ]
