# Generated by Django 5.2.13 on 2026-06-23 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0023_product_related_articles_alter_article_index_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text='/brands/<スラッグ>/ になります。半角英数とハイフン。', max_length=100, unique=True, verbose_name='スラッグ(URL)')),
                ('name', models.CharField(max_length=200, verbose_name='メーカー名(表示)')),
                ('aka', models.CharField(blank=True, help_text='英語表記/読み/旧称など。説明文・検索補助に使用(例: リファ／MTG)。', max_length=300, verbose_name='別名・読み')),
                ('match_brands', models.TextField(blank=True, help_text='このメーカーに含める商品の brand 値を1行に1つ列挙。表記ゆれや親会社名もここに入れると集約されます(例: ヤーマン / YA-MAN)。', verbose_name='集約する brand 値')),
                ('exclude_name_keywords', models.TextField(blank=True, help_text='商品名にこの語を含むものを除外。1行に1つ。別ブランドOEMの切り分け用(例: PAO)。', verbose_name='除外キーワード(商品名)')),
                ('lead', models.TextField(blank=True, help_text='ページ見出し下に表示する紹介文(プレーンテキスト/短め)。', verbose_name='リード文')),
                ('body_html', models.TextField(blank=True, help_text='商品一覧の下に表示するメーカー紹介記事。HTML可。空なら非表示。', verbose_name='紹介記事(HTML)')),
                ('image', models.ImageField(blank=True, null=True, upload_to='brands/', verbose_name='ロゴ/アイキャッチ')),
                ('image_url', models.URLField(blank=True, max_length=1000, verbose_name='画像URL(外部)')),
                ('meta_title', models.CharField(blank=True, max_length=200, verbose_name='SEOタイトル')),
                ('meta_description', models.CharField(blank=True, max_length=300, verbose_name='SEOディスクリプション')),
                ('sort_order', models.IntegerField(db_index=True, default=100, verbose_name='表示順')),
                ('is_published', models.BooleanField(default=True, verbose_name='公開')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'メーカー(ブランド)',
                'verbose_name_plural': 'メーカー(ブランド)',
                'ordering': ['sort_order', 'name'],
            },
        ),
    ]
