# Generated by Django 5.2.13 on 2026-06-30 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0025_seed_brands'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='last_rewritten_at',
            field=models.DateTimeField(blank=True, help_text='本文をリライト(全文書き換え)したときだけ明示的に更新する。公開状態・カテゴリ・インデックス等の機械的更新では動かさない（観察ステータス判定の基準）。', null=True, verbose_name='最終リライト日時'),
        ),
        migrations.AddField(
            model_name='product',
            name='last_rewritten_at',
            field=models.DateTimeField(blank=True, help_text='商品説明をリライト(全文書き換え)したときだけ明示的に更新する。在庫・価格などの機械的更新では動かさない（観察ステータス判定の基準）。', null=True, verbose_name='最終リライト日時'),
        ),
    ]
