# Generated by Django 5.2.13 on 2026-07-05 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0026_article_last_rewritten_at_product_last_rewritten_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='series',
            field=models.CharField(blank=True, db_index=True, help_text='同一メーカー内の製品シリーズ名(例: フォトプラス / Bloom / ミーゼ)。メーカーページでシリーズ別にまとめて表示されます。空欄可。', max_length=200, verbose_name='シリーズ'),
        ),
    ]
