# Generated by Django 5.2.13 on 2026-07-14 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0027_product_series'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='noindex',
            field=models.BooleanField(default=False, help_text='ONにすると meta robots noindex を出力し、サイトマップから除外します', verbose_name='検索エンジンに載せない(noindex)'),
        ),
    ]
