# Generated by Django 5.2.13 on 2026-09-08 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0028_article_noindex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='meta_title',
            field=models.CharField(blank=True, help_text='検索結果のタイトルであり、ページの見出し(H1)にもそのまま使われます(全角30文字程度推奨)。商品名＋サジェストで選定したキーワードで作ること。空欄なら商品名がタイトルにもH1にも使われます。', max_length=100, verbose_name='記事タイトル(<title>とページのH1)'),
        ),
    ]
