# Generated by Django 5.2.13 on 2026-04-25 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('female', '女性'), ('male', '男性'), ('other', 'その他')], max_length=8, verbose_name='性別'),
        ),
    ]
