# Generated by Django 5.2.13 on 2026-04-25 21:19

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_gender'),
        ('products', '0006_alter_product_affiliate_url_alter_product_amazon_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True, max_length=300, verbose_name='自己紹介'),
        ),
        migrations.AddField(
            model_name='user',
            name='icon_number',
            field=models.PositiveSmallIntegerField(blank=True, help_text='1〜10から選択', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='アバター番号'),
        ),
        migrations.AddField(
            model_name='user',
            name='instagram',
            field=models.CharField(blank=True, help_text='@は不要', max_length=30, verbose_name='Instagram'),
        ),
        migrations.AddField(
            model_name='user',
            name='tiktok',
            field=models.CharField(blank=True, help_text='@は不要', max_length=24, verbose_name='TikTok'),
        ),
        migrations.AddField(
            model_name='user',
            name='twitter',
            field=models.CharField(blank=True, help_text='@は不要', max_length=15, verbose_name='X (Twitter)'),
        ),
        migrations.AddField(
            model_name='user',
            name='website_url',
            field=models.URLField(blank=True, verbose_name='Webサイト'),
        ),
        migrations.AddField(
            model_name='user',
            name='youtube_url',
            field=models.URLField(blank=True, verbose_name='YouTube URL'),
        ),
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarked_by', to='products.product', verbose_name='気になる商品')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
            ],
            options={
                'verbose_name': '気になる',
                'verbose_name_plural': '気になる',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'product')},
            },
        ),
    ]
