# Generated by Django 5.2.13 on 2026-04-27 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_bio_user_icon_number_user_instagram_user_tiktok_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, help_text='未設定のときは下のプリセットアイコンが表示されます', null=True, upload_to='avatars/', verbose_name='プロフィールアイコン'),
        ),
    ]
