# Generated by Django 5.2.13 on 2026-06-12 06:53

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80, verbose_name='ミッション名')),
                ('description', models.TextField(blank=True, verbose_name='説明')),
                ('reward_label', models.CharField(help_text='例: 全品10%OFFクーポン / サンプルプレゼント引換券', max_length=120, verbose_name='プレゼント内容')),
                ('code_mode', models.CharField(choices=[('shared', '全員共通コード'), ('unique', '個別シリアルコード(プール)')], default='shared', max_length=8, verbose_name='コード配布方式')),
                ('shared_code', models.CharField(blank=True, help_text='配布方式が「全員共通コード」のとき、達成者全員に表示するコード', max_length=60, verbose_name='共通コード')),
                ('is_active', models.BooleanField(default=True, verbose_name='公開中')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='表示順')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'ミッション',
                'verbose_name_plural': 'ミッション',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='MissionStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('review', '口コミを投稿する'), ('helpful', '「参考になった」を獲得する'), ('bookmark', '「気になる」に登録する'), ('email_verified', 'メールアドレスを認証する'), ('profile_complete', 'プロフィールを完成させる')], max_length=24, verbose_name='アクション')),
                ('target_count', models.PositiveSmallIntegerField(default=1, help_text='この回数だけ達成すると、このステップはクリア', validators=[django.core.validators.MinValueValidator(1)], verbose_name='目標回数')),
                ('label', models.CharField(blank=True, help_text='未入力ならアクションの既定文言を使用', max_length=80, verbose_name='表示ラベル')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='表示順')),
                ('mission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='accounts.mission', verbose_name='ミッション')),
            ],
            options={
                'verbose_name': '達成ステップ',
                'verbose_name_plural': '達成ステップ',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='MissionRewardCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=60, verbose_name='コード')),
                ('assigned_at', models.DateTimeField(blank=True, null=True, verbose_name='割当日時')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_mission_codes', to=settings.AUTH_USER_MODEL, verbose_name='割当先')),
                ('mission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='codes', to='accounts.mission', verbose_name='ミッション')),
            ],
            options={
                'verbose_name': 'シリアルコード',
                'verbose_name_plural': 'シリアルコード',
                'ordering': ['id'],
                'unique_together': {('mission', 'code')},
            },
        ),
        migrations.CreateModel(
            name='UserMissionCompletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_code', models.CharField(blank=True, help_text='空の場合はコード準備中(プール枯渇)', max_length=60, verbose_name='発行コード')),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('mission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completions', to='accounts.mission', verbose_name='ミッション')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mission_completions', to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
            ],
            options={
                'verbose_name': 'ミッション達成',
                'verbose_name_plural': 'ミッション達成',
                'ordering': ['-completed_at'],
                'unique_together': {('user', 'mission')},
            },
        ),
    ]
