# Generated by Django 5.2.13 on 2026-06-12 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_mission_missionstep_missionrewardcode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermissioncompletion',
            name='seen_at',
            field=models.DateTimeField(blank=True, help_text='達成ポップアップを会員に表示済みならその日時。空なら次回表示', null=True, verbose_name='お祝い表示済み日時'),
        ),
    ]
