# Generated by Django 5.2.13 on 2026-06-12 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_usermissioncompletion_seen_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='reward_limit',
            field=models.PositiveIntegerField(blank=True, help_text='プレゼントを渡せる人数の上限。空欄で無制限。上限に達した後の達成者は対象外（受付終了）になります。', null=True, verbose_name='配布上限(先着・数量限定)'),
        ),
        migrations.AddField(
            model_name='usermissioncompletion',
            name='status',
            field=models.CharField(choices=[('awarded', 'プレゼント獲得'), ('pending', 'コード準備中'), ('sold_out', '定員終了(対象外)')], default='awarded', max_length=12, verbose_name='状態'),
        ),
        migrations.AlterField(
            model_name='usermissioncompletion',
            name='assigned_code',
            field=models.CharField(blank=True, help_text='空の場合はコード準備中、または定員終了で対象外', max_length=60, verbose_name='発行コード'),
        ),
    ]
