# Generated by Django 5.2.13 on 2026-06-12 09:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_mission_reward_limit_usermissioncompletion_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='min_review_level',
            field=models.PositiveSmallIntegerField(default=1, help_text='このレビューランク(Lv.)以上の会員のみ参加できます。1で全員参加可。', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='参加可能レビューランク'),
        ),
    ]
