# Generated by Django 5.2.13 on 2026-06-13 07:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_add_sns_link_steps'),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='max_review_level',
            field=models.PositiveSmallIntegerField(default=10, help_text='このレビューランク(Lv.)以下の会員が参加できます。10で上限なし。下限と上限を同じ値にすると、その Lv. の会員だけが対象になります（例: 下限1・上限1で Lv.1 限定キャンペーン）。', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='参加可能レビューランク(上限)'),
        ),
        migrations.AlterField(
            model_name='mission',
            name='min_review_level',
            field=models.PositiveSmallIntegerField(default=1, help_text='このレビューランク(Lv.)以上の会員が参加できます。1で下限なし。', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='参加可能レビューランク(下限)'),
        ),
    ]
