# Generated by Django 5.2.13 on 2026-06-13 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_mission_max_review_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='ends_at',
            field=models.DateTimeField(blank=True, help_text='この日時を過ぎると新規の達成受付を終了します（既存の獲得は保持）。空欄で無期限。', null=True, verbose_name='終了日時'),
        ),
        migrations.AddField(
            model_name='mission',
            name='starts_at',
            field=models.DateTimeField(blank=True, help_text='この日時以降の口コミ・参考になった・気になるの実績だけをカウントします。空欄で全期間（常設ミッション）。', null=True, verbose_name='開始日時'),
        ),
    ]
