# Generated by Django 5.2.13 on 2026-06-13 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_mission_ends_at_mission_starts_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='missionstep',
            name='action_type',
            field=models.CharField(choices=[('review', '口コミを投稿する'), ('review_with_photo', '写真付きで口コミを投稿する'), ('helpful', '「参考になった」を獲得する'), ('bookmark', '「気になる」に登録する'), ('email_verified', 'メールアドレスを認証する'), ('profile_complete', 'プロフィールを完成させる'), ('sns_twitter', 'X(Twitter)アカウントを連携する'), ('sns_instagram', 'Instagramアカウントを連携する'), ('sns_tiktok', 'TikTokアカウントを連携する'), ('sns_youtube', 'YouTubeチャンネルを連携する')], max_length=24, verbose_name='アクション'),
        ),
    ]
