# Generated by Django 5.2.13 on 2026-06-13 19:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_add_review_with_photo_step'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(help_text='ios / android / web', max_length=20, verbose_name='プラットフォーム')),
                ('push_token', models.CharField(max_length=255, verbose_name='プッシュトークン')),
                ('app_version', models.CharField(blank=True, max_length=50, verbose_name='アプリバージョン')),
                ('device_name', models.CharField(blank=True, max_length=100, verbose_name='端末名')),
                ('is_active', models.BooleanField(default=True, verbose_name='有効')),
                ('last_seen_at', models.DateTimeField(auto_now=True, verbose_name='最終アクセス')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
            ],
            options={
                'verbose_name': '端末(通知先)',
                'verbose_name_plural': '端末(通知先)',
                'ordering': ['-last_seen_at'],
                'indexes': [models.Index(fields=['user', 'is_active'], name='accounts_de_user_id_3a43c8_idx'), models.Index(fields=['push_token'], name='accounts_de_push_to_2ecf74_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'push_token'), name='unique_user_push_token')],
            },
        ),
    ]
