# Generated by Django 5.2.13 on 2026-06-15 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_device'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='hair_type',
            field=models.CharField(blank=True, choices=[('normal', '普通'), ('dry', '乾燥しやすい'), ('oily', '脂っぽい'), ('damaged', 'ダメージ毛'), ('curly', 'くせ毛'), ('fine', '細い髪'), ('thick', '太い髪'), ('other', 'その他')], max_length=16, verbose_name='髪質'),
        ),
    ]
