# Generated by Django 5.2.13 on 2026-07-30 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_user_hair_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='missionstep',
            name='min_body_length',
            field=models.PositiveSmallIntegerField(default=0, help_text='口コミ本文がこの文字数以上の投稿だけをカウントします。0で制限なし。アクションが「口コミを投稿する」「写真付きで口コミを投稿する」のときのみ有効です。', verbose_name='最低文字数'),
        ),
    ]
