# Generated by Django 5.2.13 on 2026-07-30 02:00

from django.db import migrations, models
from django.db.models import F


def backfill_approved_at(apps, schema_editor):
    # 承認制導入前の達成記録は自動配布済みのため、達成日時を承認日時として埋める
    # （管理画面で「承認待ち」と紛れないようにする）。
    UserMissionCompletion = apps.get_model("accounts", "UserMissionCompletion")
    UserMissionCompletion.objects.filter(approved_at__isnull=True).update(
        approved_at=F("completed_at")
    )


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_missionstep_min_body_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermissioncompletion',
            name='approved_at',
            field=models.DateTimeField(blank=True, help_text='運営がプレゼント配布を承認した日時。空なら承認待ち', null=True, verbose_name='運営承認日時'),
        ),
        migrations.AddField(
            model_name='usermissioncompletion',
            name='code_sent_at',
            field=models.DateTimeField(blank=True, help_text='承認後にコード案内メールを送信した日時。空なら未送信', null=True, verbose_name='コードメール送信日時'),
        ),
        migrations.AlterField(
            model_name='usermissioncompletion',
            name='status',
            field=models.CharField(choices=[('waiting', '承認待ち(運営確認中)'), ('awarded', 'プレゼント獲得'), ('pending', 'コード準備中'), ('sold_out', '定員終了(対象外)')], default='awarded', max_length=12, verbose_name='状態'),
        ),
        migrations.RunPython(backfill_approved_at, migrations.RunPython.noop),
    ]
