# Generated by Django 5.2.13 on 2026-04-27 10:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0010_product_cautions_product_last_verified_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(db_index=True, max_length=200, verbose_name='ターゲットキーワード')),
                ('title', models.CharField(max_length=300, verbose_name='記事タイトル')),
                ('content', models.TextField(verbose_name='記事本文(HTML)')),
                ('excerpt', models.TextField(blank=True, max_length=500, verbose_name='抜粋')),
                ('yakkihou_check', models.JSONField(blank=True, default=dict, help_text='例: {"violations": [], "warnings": ["XXX"], "ok": true}', verbose_name='薬機法チェック結果')),
                ('yakkihou_passed', models.BooleanField(default=False, verbose_name='薬機法OK')),
                ('status', models.CharField(choices=[('draft', '下書き(AI生成直後)'), ('pending_review', '人間確認待ち'), ('approved', '承認済(未公開)'), ('published', '公開中'), ('rejected', '却下')], db_index=True, default='draft', max_length=20, verbose_name='公開ステータス')),
                ('ai_generated_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='AI生成日時')),
                ('human_reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='人間確認日時')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('human_reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_product_articles', to=settings.AUTH_USER_MODEL, verbose_name='確認者')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_articles', to='products.product', verbose_name='対象商品')),
                ('published_article', models.OneToOneField(blank=True, help_text='承認後、公開Article(products.Article)として登録するリンク', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_source', to='products.article', verbose_name='公開記事')),
            ],
            options={
                'verbose_name': 'AI生成記事',
                'verbose_name_plural': 'AI生成記事',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ArticleGenerationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=200, verbose_name='キーワード')),
                ('source_snapshot', models.JSONField(default=dict, help_text='生成時の商品DB情報の完全コピー(後から検証可能)', verbose_name='商品情報スナップショット')),
                ('prompt_template', models.CharField(blank=True, max_length=100, verbose_name='プロンプトテンプレ')),
                ('full_prompt', models.TextField(blank=True, help_text='AIに渡した最終プロンプト全文', verbose_name='最終プロンプト')),
                ('ai_provider', models.CharField(blank=True, help_text='anthropic / openai / google 等', max_length=50, verbose_name='AIプロバイダ')),
                ('ai_model', models.CharField(blank=True, help_text='claude-sonnet-4-6 / gpt-4o 等', max_length=100, verbose_name='AIモデル')),
                ('ai_temperature', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Temperature')),
                ('raw_output', models.TextField(blank=True, verbose_name='AI生出力')),
                ('parsed_title', models.CharField(blank=True, max_length=300, verbose_name='解析タイトル')),
                ('parsed_content', models.TextField(blank=True, verbose_name='解析本文')),
                ('tokens_input', models.IntegerField(blank=True, null=True, verbose_name='入力トークン')),
                ('tokens_output', models.IntegerField(blank=True, null=True, verbose_name='出力トークン')),
                ('duration_ms', models.IntegerField(blank=True, null=True, verbose_name='実行時間ms')),
                ('cost_usd', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True, verbose_name='コストUSD')),
                ('hallucination_check', models.JSONField(default=dict, help_text='DBに無い情報が出力に混入していないかの検査結果', verbose_name='ハルシネーション検査')),
                ('yakkihou_check_log', models.JSONField(default=dict, verbose_name='薬機法チェックログ')),
                ('success', models.BooleanField(db_index=True, default=True, verbose_name='成功')),
                ('error_message', models.TextField(blank=True, verbose_name='エラー詳細')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generation_logs', to='products.product', verbose_name='対象商品')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generation_logs', to='aiarticles.productarticle', verbose_name='生成記事')),
            ],
            options={
                'verbose_name': '生成ログ',
                'verbose_name_plural': '生成ログ',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductArticleKeyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=200, verbose_name='キーワード')),
                ('search_volume', models.IntegerField(blank=True, null=True, verbose_name='月間検索ボリューム')),
                ('difficulty', models.IntegerField(blank=True, null=True, verbose_name='難易度(1-100)')),
                ('priority', models.IntegerField(db_index=True, default=0, help_text='数値が大きいほど優先', verbose_name='優先度')),
                ('is_generated', models.BooleanField(db_index=True, default=False, verbose_name='記事生成済み')),
                ('notes', models.TextField(blank=True, verbose_name='メモ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_keywords', to='products.product', verbose_name='商品')),
            ],
            options={
                'verbose_name': '商品キーワード',
                'verbose_name_plural': '商品キーワード',
                'ordering': ['-priority', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='productarticle',
            index=models.Index(fields=['status', '-created_at'], name='aiarticles__status_3d4c55_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='productarticlekeyword',
            unique_together={('product', 'keyword')},
        ),
    ]
