# Generated by Django 5.2.13 on 2026-04-27 13:22

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aiarticles', '0001_initial'),
        ('products', '0011_article_seo_check_result_article_seo_keyword'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SeoKeywordStrategy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(db_index=True, help_text='例: 美顔器, ドライヤー, 脱毛器', max_length=100, verbose_name='カテゴリ名')),
                ('keyword', models.CharField(db_index=True, max_length=200, verbose_name='対策キーワード')),
                ('search_intent', models.TextField(blank=True, help_text='このキーワードで検索するユーザーが何を求めているか', verbose_name='検索意図')),
                ('article_type', models.CharField(choices=[('review', '口コミ・レビュー記事'), ('effect', '効果・検証記事'), ('comparison', '比較記事'), ('ranking', 'おすすめ・ランキング記事'), ('howto', '使い方記事'), ('faq', '疑問解決記事')], db_index=True, default='review', max_length=20, verbose_name='記事タイプ')),
                ('search_volume', models.PositiveIntegerField(default=0, verbose_name='月間検索ボリューム')),
                ('commercial_intent_score', models.PositiveSmallIntegerField(default=3, help_text='1=情報収集 5=購入直前', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='商用意図スコア')),
                ('competition_score', models.PositiveSmallIntegerField(default=3, help_text='1=狙いやすい 5=超激戦', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='競合強度')),
                ('priority_score', models.FloatField(db_index=True, default=0, help_text='自動計算: 検索ボリューム × 商用意図 / 競合強度', verbose_name='優先度スコア')),
                ('status', models.CharField(choices=[('idea', '候補'), ('planned', '作成予定'), ('writing', '執筆中'), ('generated', 'AI生成済み'), ('checking', '薬機法/SEO確認中'), ('published', '公開済み'), ('rewrite', 'リライト対象'), ('hold', '保留')], db_index=True, default='idea', max_length=20, verbose_name='ステータス')),
                ('target_url', models.URLField(blank=True, help_text='公開予定 or 公開済みURL', max_length=500, verbose_name='公開URL')),
                ('link_anchor_text', models.CharField(blank=True, max_length=200, verbose_name='推奨アンカーテキスト')),
                ('memo', models.TextField(blank=True, verbose_name='メモ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_seo_keywords', to=settings.AUTH_USER_MODEL, verbose_name='担当者')),
                ('internal_link_targets', models.ManyToManyField(blank=True, related_name='incoming_links', to='aiarticles.seokeywordstrategy', verbose_name='内部リンク先')),
                ('parent_keyword', models.ForeignKey(blank=True, help_text='例: 「美顔器 おすすめ」が「美顔器 効果」の親', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='aiarticles.seokeywordstrategy', verbose_name='親キーワード')),
                ('related_article', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seo_keywords', to='products.article', verbose_name='関連記事')),
                ('related_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seo_keywords', to='products.product', verbose_name='関連商品')),
            ],
            options={
                'verbose_name': 'SEOキーワード戦略',
                'verbose_name_plural': 'SEOキーワード戦略',
                'ordering': ['-priority_score', '-updated_at'],
                'indexes': [models.Index(fields=['status', '-priority_score'], name='aiarticles__status_f79218_idx'), models.Index(fields=['category', 'article_type'], name='aiarticles__categor_e469be_idx')],
            },
        ),
    ]
