# Generated by Django 5.2.13 on 2026-04-27 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aiarticles', '0002_seokeywordstrategy'),
    ]

    operations = [
        migrations.CreateModel(
            name='NgExpressionRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pattern', models.CharField(max_length=200, unique=True, verbose_name='NGワード/正規表現')),
                ('is_regex', models.BooleanField(default=False, verbose_name='正規表現として扱う')),
                ('risk_category', models.CharField(choices=[('yakuji', '薬機法違反'), ('keihyo', '景品表示法違反'), ('medical', '医療表現'), ('absolute', '断定表現'), ('exaggeration', '誇張・優位表現'), ('comparison', '比較優位'), ('other', 'その他')], db_index=True, max_length=20, verbose_name='リスク分類')),
                ('severity', models.CharField(choices=[('high', '高(必ず修正)'), ('medium', '中(要確認)'), ('low', '低(可能なら修正)')], db_index=True, default='high', max_length=10, verbose_name='深刻度')),
                ('reason', models.TextField(verbose_name='理由')),
                ('suggestion', models.TextField(blank=True, verbose_name='推奨言い換え')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='有効')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'NG表現ルール',
                'verbose_name_plural': 'NG表現ルール',
                'ordering': ['-severity', 'risk_category', 'pattern'],
            },
        ),
    ]
