# Generated by Django 5.2.13 on 2026-07-10 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SurveyResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('survey_slug', models.SlugField(max_length=64, verbose_name='アンケート')),
                ('answers', models.JSONField(blank=True, default=dict, verbose_name='回答')),
                ('reason', models.TextField(blank=True, max_length=300, verbose_name='理由・感想')),
                ('is_approved', models.BooleanField(default=False, help_text='自由記述コメントを結果として公開してよい場合にチェック', verbose_name='コメント公開可')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='削除(集計から除外)')),
                ('ip_hash', models.CharField(blank=True, db_index=True, max_length=64)),
                ('user_agent', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='投稿日時')),
            ],
            options={
                'verbose_name': 'アンケート回答',
                'verbose_name_plural': 'アンケート回答',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['survey_slug', 'is_deleted'], name='surveys_sur_survey__3075d7_idx')],
            },
        ),
    ]
