# Generated by Django 5.2.13 on 2026-04-26 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='お名前')),
                ('email', models.EmailField(max_length=254, verbose_name='メールアドレス')),
                ('subject', models.CharField(max_length=200, verbose_name='件名')),
                ('body', models.TextField(verbose_name='お問い合わせ内容')),
                ('is_read', models.BooleanField(db_index=True, default=False, verbose_name='既読')),
                ('is_replied', models.BooleanField(db_index=True, default=False, verbose_name='返信済み')),
                ('admin_notes', models.TextField(blank=True, help_text='ユーザーには見えない管理用メモ', verbose_name='管理メモ')),
                ('ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP')),
                ('user_agent', models.CharField(blank=True, max_length=500, verbose_name='User-Agent')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='受信日時')),
                ('replied_at', models.DateTimeField(blank=True, null=True, verbose_name='返信日時')),
            ],
            options={
                'verbose_name': 'お問い合わせ',
                'verbose_name_plural': 'お問い合わせ',
                'ordering': ['-created_at'],
            },
        ),
    ]
