# Generated by Django 5.2.13 on 2026-06-25 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LegalDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.SlugField(choices=[('terms', '利用規約'), ('privacy', 'プライバシーポリシー'), ('community', 'コミュニティガイドライン')], help_text='WEB/アプリはこの種別で文書を取得します。', max_length=20, unique=True, verbose_name='種別')),
                ('eyebrow', models.CharField(blank=True, help_text='見出し上の小さな英字(例: Terms)。空欄可。', max_length=40, verbose_name='英字ラベル')),
                ('title', models.CharField(max_length=100, verbose_name='タイトル')),
                ('body', models.TextField(help_text='セマンティックHTML。見出しは <h2>、小見出しは <h3>、段落は <p>、箇条書きは <ul><li>、番号付きは <ol><li>、リンクは <a href> を使用。class属性は不要(自動でデザインが適用されます)。', verbose_name='本文(HTML)')),
                ('enacted_on', models.DateField(blank=True, null=True, verbose_name='制定日')),
                ('revised_on', models.DateField(blank=True, null=True, verbose_name='最終改定日')),
                ('is_published', models.BooleanField(default=True, help_text='オフにするとWEB・アプリ双方で非表示(404)になります。', verbose_name='公開')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='最終更新')),
            ],
            options={
                'verbose_name': '規約・ポリシー',
                'verbose_name_plural': '規約・ポリシー',
                'ordering': ['doc_type'],
            },
        ),
    ]
