# Generated by Django 5.2.13 on 2026-04-26 15:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(db_index=True, max_length=500, verbose_name='URL')),
                ('method', models.CharField(default='GET', max_length=10, verbose_name='メソッド')),
                ('status_code', models.PositiveSmallIntegerField(db_index=True, null=True, verbose_name='ステータスコード')),
                ('ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP')),
                ('user_agent', models.CharField(blank=True, max_length=500, verbose_name='User-Agent')),
                ('referer', models.CharField(blank=True, max_length=500, verbose_name='リファラ')),
                ('is_bot', models.BooleanField(db_index=True, default=False, verbose_name='Bot判定')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='日時')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
            ],
            options={
                'verbose_name': 'アクセスログ',
                'verbose_name_plural': 'アクセスログ',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at', 'url'], name='analytics_a_created_3b6e22_idx')],
            },
        ),
    ]
