# Generated by Django 5.2.13 on 2026-06-25 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='作業タイトル')),
                ('status', models.CharField(choices=[('success', '完了'), ('info', '情報'), ('warning', '注意'), ('error', 'エラー')], db_index=True, default='success', max_length=10, verbose_name='状態')),
                ('summary', models.CharField(blank=True, help_text='一覧に表示する1行サマリー。', max_length=500, verbose_name='概要')),
                ('body', models.TextField(blank=True, help_text='詳細レポート。Markdownで記述すると整形表示される。', verbose_name='作業報告')),
                ('files_changed', models.TextField(blank=True, help_text='1行1ファイル。', verbose_name='変更ファイル')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='報告日時')),
            ],
            options={
                'verbose_name': '作業報告',
                'verbose_name_plural': '作業報告',
                'ordering': ['-created_at'],
            },
        ),
    ]
