# Generated by Django 5.2.13 on 2026-06-29 20:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_workreport'),
        ('products', '0025_seed_brands'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleMetricSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateField(db_index=True, verbose_name='期間開始')),
                ('period_end', models.DateField(db_index=True, verbose_name='期間終了')),
                ('fetched_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='取得日時')),
                ('total_clicks', models.IntegerField(default=0, verbose_name='総クリック(GSC)')),
                ('total_impressions', models.IntegerField(default=0, verbose_name='総表示回数(GSC)')),
                ('avg_ctr', models.FloatField(default=0.0, verbose_name='平均CTR%(GSC)')),
                ('avg_position', models.FloatField(default=0.0, verbose_name='平均掲載順位(GSC)')),
                ('total_sessions', models.IntegerField(default=0, verbose_name='総セッション(GA4)')),
                ('total_page_views', models.IntegerField(default=0, verbose_name='総PV(GA4)')),
                ('avg_bounce_rate', models.FloatField(default=0.0, verbose_name='平均直帰率(GA4)')),
                ('note', models.CharField(blank=True, max_length=300, verbose_name='メモ')),
            ],
            options={
                'verbose_name': '記事パフォーマンス・スナップショット',
                'verbose_name_plural': '記事パフォーマンス・スナップショット',
                'ordering': ['-fetched_at'],
            },
        ),
        migrations.CreateModel(
            name='ArticleMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(db_index=True, max_length=500, verbose_name='パス')),
                ('title', models.CharField(blank=True, max_length=300, verbose_name='タイトル')),
                ('content_type', models.CharField(choices=[('article', '記事'), ('product', '商品'), ('category', 'カテゴリ'), ('page', '固定ページ'), ('other', 'その他')], db_index=True, default='other', max_length=12, verbose_name='種別')),
                ('impressions', models.IntegerField(db_index=True, default=0, verbose_name='表示回数')),
                ('clicks', models.IntegerField(default=0, verbose_name='クリック')),
                ('ctr', models.FloatField(default=0.0, verbose_name='CTR%')),
                ('position', models.FloatField(default=0.0, verbose_name='平均順位')),
                ('sessions', models.IntegerField(db_index=True, default=0, verbose_name='セッション')),
                ('page_views', models.IntegerField(default=0, verbose_name='PV')),
                ('active_users', models.IntegerField(default=0, verbose_name='ユーザー数')),
                ('bounce_rate', models.FloatField(default=0.0, verbose_name='直帰率')),
                ('avg_duration_sec', models.FloatField(default=0.0, verbose_name='平均滞在秒')),
                ('keywords', models.JSONField(blank=True, default=list, verbose_name='流入キーワード')),
                ('article', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='metric_rows', to='products.article', verbose_name='記事')),
                ('snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='analytics.articlemetricsnapshot', verbose_name='スナップショット')),
            ],
            options={
                'verbose_name': '記事パフォーマンス',
                'verbose_name_plural': '記事パフォーマンス',
                'ordering': ['-impressions'],
                'indexes': [models.Index(fields=['snapshot', '-impressions'], name='analytics_a_snapsho_7186a2_idx')],
            },
        ),
    ]
