# Generated by Django 5.2.13 on 2026-06-30 21:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0003_articlemetricsnapshot_articlemetric'),
        ('products', '0025_seed_brands'),
    ]

    operations = [
        migrations.CreateModel(
            name='TriageRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateField(db_index=True, verbose_name='期間開始')),
                ('period_end', models.DateField(db_index=True, verbose_name='期間終了')),
                ('fetched_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='取得日時')),
                ('total_articles', models.IntegerField(default=0, verbose_name='対象ページ数')),
                ('count_quick_win', models.IntegerField(default=0, verbose_name='quick_win 件数')),
                ('count_needs_work', models.IntegerField(default=0, verbose_name='needs_work 件数')),
                ('count_performing', models.IntegerField(default=0, verbose_name='performing 件数')),
                ('count_dead', models.IntegerField(default=0, verbose_name='dead 件数')),
                ('sitemap_url', models.CharField(blank=True, max_length=500, verbose_name='サイトマップURL')),
            ],
            options={
                'verbose_name': 'GSCトリアージ実行',
                'verbose_name_plural': 'GSCトリアージ実行',
                'ordering': ['-fetched_at'],
            },
        ),
        migrations.CreateModel(
            name='ArticleTriage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(db_index=True, max_length=500, verbose_name='URL')),
                ('bucket', models.CharField(choices=[('quick_win', 'quick_win（あと一歩・最優先）'), ('needs_work', 'needs_work（検索意図のズレ）'), ('performing', 'performing（すでに上位）'), ('dead', 'dead（統合/削除候補）')], db_index=True, max_length=12, verbose_name='バケット')),
                ('impressions', models.IntegerField(default=0, verbose_name='表示回数')),
                ('clicks', models.IntegerField(default=0, verbose_name='クリック')),
                ('ctr', models.FloatField(default=0.0, verbose_name='CTR%')),
                ('avg_position', models.FloatField(default=0.0, verbose_name='平均掲載順位')),
                ('best_query', models.CharField(blank=True, max_length=300, verbose_name='最上位クエリ')),
                ('best_query_position', models.FloatField(blank=True, null=True, verbose_name='最上位クエリ順位')),
                ('best_query_impressions', models.IntegerField(default=0, verbose_name='最上位クエリ表示回数')),
                ('num_queries', models.IntegerField(default=0, verbose_name='クエリ数')),
                ('in_sitemap', models.BooleanField(default=False, verbose_name='サイトマップ掲載')),
                ('article', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='triage_rows', to='products.article', verbose_name='記事')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='analytics.triagerun', verbose_name='トリアージ実行')),
            ],
            options={
                'verbose_name': '記事トリアージ',
                'verbose_name_plural': '記事トリアージ',
                'ordering': ['bucket', 'best_query_position'],
                'indexes': [models.Index(fields=['run', 'bucket'], name='analytics_a_run_id_f1012d_idx'), models.Index(fields=['bucket'], name='analytics_a_bucket_34c011_idx'), models.Index(fields=['best_query_position'], name='analytics_a_best_qu_67ffa6_idx')],
            },
        ),
    ]
