# Generated by Django 5.2.13 on 2026-06-30 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0004_triagerun_articletriage'),
    ]

    operations = [
        migrations.AddField(
            model_name='articletriage',
            name='days_since_update',
            field=models.IntegerField(blank=True, null=True, verbose_name='更新からの経過日数'),
        ),
        migrations.AddField(
            model_name='articletriage',
            name='last_updated',
            field=models.DateTimeField(blank=True, null=True, verbose_name='更新日(実行時スナップショット)'),
        ),
        migrations.AddField(
            model_name='articletriage',
            name='observation_status',
            field=models.CharField(blank=True, choices=[('observing', 'observing（様子見・反映ラグ中）'), ('evaluable', 'evaluable（評価中）'), ('settled', 'settled（判定済み）'), ('unknown', 'unknown（更新日不明）')], db_index=True, max_length=12, null=True, verbose_name='観察ステータス'),
        ),
    ]
