# Generated by Django 5.2.13 on 2026-06-30 23:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0005_articletriage_days_since_update_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlaybookRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(max_length=60, unique=True, verbose_name='キー')),
                ('category', models.CharField(choices=[('title', 'タイトル/H1'), ('intent', '検索意図'), ('structure', '構成・網羅性'), ('internal_link', '内部リンク'), ('specificity', '具体性・一次情報'), ('anti', '避けるべきパターン')], db_index=True, max_length=16, verbose_name='分類')),
                ('title', models.CharField(max_length=200, verbose_name='ルール名')),
                ('description', models.TextField(blank=True, verbose_name='説明')),
                ('check_item', models.CharField(blank=True, help_text='レビュー画面のチェックリストに出す1行。', max_length=300, verbose_name='チェック項目')),
                ('evidence', models.JSONField(blank=True, default=dict, help_text='live/dead の偏在度など根拠データ。', verbose_name='エビデンス')),
                ('priority', models.IntegerField(default=100, help_text='小さいほど上位', verbose_name='優先度')),
                ('is_active', models.BooleanField(default=True, verbose_name='有効')),
                ('is_antipattern', models.BooleanField(default=False, verbose_name='避けるべきパターン')),
                ('verified', models.BooleanField(default=False, verbose_name='実データ検証済み')),
                ('verification_note', models.TextField(blank=True, verbose_name='検証メモ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新')),
                ('source_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='playbook_rules', to='analytics.triagerun', verbose_name='生成元トリアージ実行')),
            ],
            options={
                'verbose_name': 'プレイブック項目',
                'verbose_name_plural': 'プレイブック項目',
                'ordering': ['priority', 'category'],
            },
        ),
    ]
