# Generated by Django 5.2.13 on 2026-07-01 00:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0006_playbookrule'),
        ('products', '0026_article_last_rewritten_at_product_last_rewritten_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='RewriteDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_query', models.CharField(blank=True, max_length=300, verbose_name='押し上げ対象クエリ')),
                ('src_best_position', models.FloatField(blank=True, null=True, verbose_name='着手時 順位')),
                ('src_impressions', models.IntegerField(default=0, verbose_name='着手時 表示回数')),
                ('status', models.CharField(choices=[('pending', '未着手'), ('instructed', '指示書生成済'), ('drafting', '執筆中'), ('in_review', 'レビュー待ち'), ('approved', '承認'), ('applied', '反映済'), ('rejected', '却下')], db_index=True, default='pending', max_length=12, verbose_name='状態')),
                ('instructions', models.TextField(blank=True, verbose_name='リライト指示書')),
                ('checklist', models.JSONField(blank=True, default=list, verbose_name='チェックリスト')),
                ('playbook_refs', models.JSONField(blank=True, default=list, verbose_name='参照プレイブック項目')),
                ('draft_title', models.CharField(blank=True, max_length=500, verbose_name='案タイトル')),
                ('draft_content', models.TextField(blank=True, verbose_name='案本文(HTML)')),
                ('diff_summary', models.TextField(blank=True, verbose_name='変更点の要約')),
                ('reviewer_note', models.TextField(blank=True, verbose_name='レビューメモ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成')),
                ('instructed_at', models.DateTimeField(blank=True, null=True, verbose_name='指示書生成')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='レビュー')),
                ('applied_at', models.DateTimeField(blank=True, null=True, verbose_name='反映')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rewrite_drafts', to='products.article', verbose_name='記事')),
                ('source_triage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rewrite_drafts', to='analytics.articletriage', verbose_name='着手時トリアージ')),
            ],
            options={
                'verbose_name': 'リライト下書き',
                'verbose_name_plural': 'リライト下書き',
                'ordering': ['-src_impressions', '-created_at'],
                'indexes': [models.Index(fields=['status'], name='analytics_r_status_e929dd_idx'), models.Index(fields=['article', '-created_at'], name='analytics_r_article_9b7ae5_idx')],
            },
        ),
    ]
