# Generated by Django 5.2.13 on 2026-07-01 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0007_rewritedraft'),
    ]

    operations = [
        migrations.AddField(
            model_name='articletriage',
            name='queries',
            field=models.JSONField(blank=True, default=list, verbose_name='獲得クエリ一覧'),
        ),
        migrations.AddField(
            model_name='rewritedraft',
            name='query_portfolio',
            field=models.JSONField(blank=True, default=list, verbose_name='獲得クエリ一覧'),
        ),
        migrations.AddField(
            model_name='rewritedraft',
            name='target_grow',
            field=models.JSONField(blank=True, default=list, verbose_name='成長クエリ(grow)'),
        ),
        migrations.AddField(
            model_name='rewritedraft',
            name='target_keep',
            field=models.JSONField(blank=True, default=list, verbose_name='維持クエリ(keep)'),
        ),
        migrations.AlterField(
            model_name='rewritedraft',
            name='target_query',
            field=models.CharField(blank=True, max_length=300, verbose_name='押し上げ対象クエリ(旧・grow代表)'),
        ),
    ]
