# Generated by Django 5.2.13 on 2026-07-01 02:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0008_articletriage_queries_rewritedraft_query_portfolio_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentGap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_query', models.CharField(blank=True, max_length=300, verbose_name='対象クエリ(grow代表)')),
                ('competitor_urls', models.JSONField(blank=True, default=list, help_text='上位表示の競合URL 2〜3本。["https://...", ...] 形式。取得・解析はしない。', verbose_name='競合URL(人が貼る)')),
                ('self_outline', models.JSONField(blank=True, default=dict, help_text='H2/H3見出し・FAQ有無をアプリが決定論抽出したもの。', verbose_name='自記事アウトライン')),
                ('gap_findings', models.TextField(blank=True, help_text='Claude Code/人が競合を読んで記入。1行1要素。増量の全列挙ではなく本質要素のみ。', verbose_name='ギャップ(欠けている本質要素)')),
                ('gap_decisions', models.JSONField(blank=True, default=list, help_text='[{"item":..., "reflect":true/false, "primary_info":true/false}] 反映すると選んだ項目だけが指示書に渡る（増量の歯止め）。', verbose_name='採否')),
                ('status', models.CharField(choices=[('pending', '未着手'), ('urls_set', '競合URL設定済'), ('analyzed', 'ギャップ記入済'), ('reviewed', '採否確定済')], db_index=True, default='pending', max_length=12, verbose_name='状態')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新')),
                ('rewrite_draft', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='content_gap', to='analytics.rewritedraft', verbose_name='リライト下書き')),
            ],
            options={
                'verbose_name': 'コンテンツギャップ(上位比較)',
                'verbose_name_plural': 'コンテンツギャップ(上位比較)',
            },
        ),
    ]
