# Generated by Django 5.2.13 on 2026-07-01 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0009_contentgap'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentgap',
            name='competitor_content',
            field=models.TextField(blank=True, help_text='競合ページを開いて本文をコピペで貼り付け。bot取得はブロックされるサイトが多いため、人が貼ったこの本文を Claude Code が分析する（複数競合は見出し等で区切って貼ってよい）。', verbose_name='競合ページ本文(人がコピペ)'),
        ),
        migrations.AlterField(
            model_name='contentgap',
            name='competitor_urls',
            field=models.JSONField(blank=True, default=list, help_text='上位表示の競合URL 2〜3本。どの競合と戦うかの記録。', verbose_name='競合URL(人が貼る・記録用)'),
        ),
    ]
