# Generated by Django 5.2.13 on 2026-07-01 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0010_contentgap_competitor_content_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contentgap',
            name='competitor_content',
        ),
        migrations.AddField(
            model_name='contentgap',
            name='competitor_bodies',
            field=models.JSONField(blank=True, default=dict, help_text='{URL: 本文} の辞書。競合URLの数だけ本文欄が出るので、各URLのページ本文をコピペする。bot取得はブロックされるサイトが多いため、人が貼ったこの本文を Claude Code が分析する。', verbose_name='競合ページ本文(URLごと・人がコピペ)'),
        ),
    ]
