# Generated by Django 5.2.13 on 2026-07-01 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0011_remove_contentgap_competitor_content_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompletedRewriteDraft',
            fields=[
            ],
            options={
                'verbose_name': 'リライト完了',
                'verbose_name_plural': 'リライト完了一覧',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('analytics.rewritedraft',),
        ),
    ]
