# Generated by Django 5.2.13 on 2026-07-02 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0012_completedrewritedraft'),
    ]

    operations = [
        migrations.CreateModel(
            name='RewriteEval',
            fields=[
            ],
            options={
                'verbose_name': 'リライト効果測定',
                'verbose_name_plural': 'リライト効果測定',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('analytics.rewritedraft',),
        ),
        migrations.AddField(
            model_name='rewritedraft',
            name='days_since_applied',
            field=models.IntegerField(blank=True, null=True, verbose_name='反映後経過日数'),
        ),
        migrations.AddField(
            model_name='rewritedraft',
            name='eval_status',
            field=models.CharField(choices=[('pending_eval', '結果待ち'), ('improved', '改善'), ('reached_p1', '1ページ目到達'), ('flat', '横ばい'), ('declined', '悪化')], db_index=True, default='pending_eval', max_length=14, verbose_name='効果判定'),
        ),
        migrations.AddField(
            model_name='rewritedraft',
            name='grow_after',
            field=models.FloatField(blank=True, null=True, verbose_name='grow反映後順位'),
        ),
        migrations.AddField(
            model_name='rewritedraft',
            name='grow_before',
            field=models.FloatField(blank=True, null=True, verbose_name='grow反映前順位'),
        ),
        migrations.AddField(
            model_name='rewritedraft',
            name='keep_damaged',
            field=models.BooleanField(db_index=True, default=False, verbose_name='keep毀損'),
        ),
        migrations.AddField(
            model_name='rewritedraft',
            name='keep_detail',
            field=models.JSONField(blank=True, default=list, verbose_name='keep毀損詳細'),
        ),
        migrations.AddField(
            model_name='rewritedraft',
            name='measured_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='測定実行日時'),
        ),
    ]
