# Generated by Django 5.2.13 on 2026-07-02 21:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0013_rewriteeval_rewritedraft_days_since_applied_and_more'),
        ('products', '0026_article_last_rewritten_at_product_last_rewritten_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='rewritedraft',
            name='is_manual',
            field=models.BooleanField(db_index=True, default=False, verbose_name='手動追加'),
        ),
        migrations.AddField(
            model_name='rewritedraft',
            name='reference_article',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rewrite_reference_for', to='products.article', verbose_name='基準記事(お手本)'),
        ),
    ]
