# Generated by Django 5.2.13 on 2026-07-14 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0014_rewritedraft_is_manual_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RewriteTactic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=60, unique=True, verbose_name='戦術キー')),
                ('label', models.CharField(max_length=200, verbose_name='戦術名')),
                ('description', models.CharField(blank=True, max_length=300, verbose_name='説明')),
                ('n_reached_p1', models.IntegerField(default=0, verbose_name='1ページ目到達')),
                ('n_improved', models.IntegerField(default=0, verbose_name='改善')),
                ('n_flat', models.IntegerField(default=0, verbose_name='横ばい')),
                ('n_declined', models.IntegerField(default=0, verbose_name='悪化')),
                ('n_keep_damaged', models.IntegerField(default=0, verbose_name='keep毀損 同時発生')),
                ('samples', models.JSONField(blank=True, default=list, verbose_name='根拠サンプル')),
                ('note', models.TextField(blank=True, verbose_name='所見(人間/Claude Code追記)')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新')),
            ],
            options={
                'verbose_name': 'リライト戦術 成績',
                'verbose_name_plural': 'リライト戦術 成績（学習ループ）',
                'ordering': ['-n_reached_p1', '-n_improved'],
            },
        ),
        migrations.AddField(
            model_name='rewritedraft',
            name='applied_tactics',
            field=models.JSONField(blank=True, default=list, verbose_name='適用した戦術'),
        ),
        migrations.AddField(
            model_name='rewritedraft',
            name='lesson',
            field=models.TextField(blank=True, verbose_name='学び(判定確定後)'),
        ),
        migrations.AddField(
            model_name='rewritedraft',
            name='lesson_recorded_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='学び記録日時'),
        ),
    ]
