# Generated by Django 5.2.13 on 2026-07-14 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0015_rewritetactic_rewritedraft_applied_tactics_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentgap',
            name='external_analysis',
            field=models.TextField(blank=True, help_text='作業台の「GPTに渡すプロンプト」をコピーしてGPT(ブラウジング可)に投げ、返答をここへそのまま貼り付ける。ギャップ分析と指示書がこの内容も材料にする。', verbose_name='GPT分析結果(貼り付け)'),
        ),
    ]
