# Generated by Django 5.2.13 on 2026-09-06 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0016_contentgap_external_analysis'),
    ]

    operations = [
        migrations.CreateModel(
            name='RevenueEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_month', models.CharField(db_index=True, help_text='YYYY-MM 形式(例: 2026-09)', max_length=7, verbose_name='対象月')),
                ('source', models.CharField(choices=[('rakuten', '楽天アフィリエイト'), ('amazon', 'Amazonアソシエイト'), ('adsense', 'AdSense'), ('other', 'その他')], max_length=16, verbose_name='収益源')),
                ('amount', models.PositiveIntegerField(verbose_name='金額(円)')),
                ('is_confirmed', models.BooleanField(default=True, help_text='OFF=速報値/見込み。確定したら金額を直してONにする', verbose_name='確定額')),
                ('memo', models.CharField(blank=True, max_length=200, verbose_name='メモ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='入力日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
            options={
                'verbose_name': '収益記録',
                'verbose_name_plural': '収益記録',
                'ordering': ['-year_month', 'source'],
                'constraints': [models.UniqueConstraint(fields=('year_month', 'source'), name='unique_revenue_month_source')],
            },
        ),
    ]
