# Generated by Django 5.2.13 on 2026-09-08 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0018_rewritedraft_qa_result'),
    ]

    operations = [
        migrations.CreateModel(
            name='EditorNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('rewrite', 'リライト案'), ('article', '新規記事'), ('product_v2', '商品記事v2')], db_index=True, max_length=12, verbose_name='対象')),
                ('target_id', models.IntegerField(db_index=True, help_text='RewriteDraft.id / Article.id / Product.pk', verbose_name='対象ID')),
                ('slug', models.CharField(blank=True, max_length=500, verbose_name='スラッグ')),
                ('target_title', models.CharField(blank=True, max_length=500, verbose_name='対象タイトル')),
                ('quote', models.TextField(blank=True, help_text='空＝記事全体への指摘', verbose_name='指摘箇所（本文からの引用）')),
                ('comment', models.TextField(verbose_name='修正指示')),
                ('category', models.CharField(choices=[('reader_value', '読者価値・切り口'), ('structure', '構成・見出しの流れ'), ('tone', '文章表現・トーン'), ('fact', '事実・数値の正確さ'), ('seo', 'タイトル・メタ・SEO'), ('product', '商品選定・価格'), ('links', '内部リンク・回遊'), ('compliance', '薬機法・景表法'), ('format', '書式・レイアウト'), ('other', 'その他')], db_index=True, default='other', max_length=16, verbose_name='指摘の種類')),
                ('assignee', models.CharField(blank=True, choices=[('writer', '新規執筆担当（ふみちゃん）'), ('product_writer', '商品記事v2担当（アズ）'), ('followup', 'リライト後続処理（なお姉）'), ('qa', '検品担当（リン様）')], max_length=16, verbose_name='担当')),
                ('status', models.CharField(choices=[('open', '対応待ち'), ('fixed', '修正済'), ('dismissed', '対応不要')], db_index=True, default='open', max_length=10, verbose_name='状態')),
                ('sent_back_at', models.DateTimeField(blank=True, null=True, verbose_name='担当へ差し戻し')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='対応完了')),
                ('resolution', models.TextField(blank=True, verbose_name='担当の対応内容')),
                ('lesson', models.TextField(blank=True, verbose_name='次に活かす学び')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='作成')),
            ],
            options={
                'verbose_name': '記事の修正指示',
                'verbose_name_plural': '記事の修正指示（レビュー）',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['kind', 'target_id'], name='analytics_e_kind_4c6c2a_idx'), models.Index(fields=['status', 'assignee'], name='analytics_e_status_b8af69_idx')],
            },
        ),
    ]
