# Generated by Django 5.2.13 on 2026-09-08 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0019_editornote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='editornote',
            name='assignee',
            field=models.CharField(blank=True, choices=[('writer', '新規執筆担当（ふみちゃん）'), ('product_writer', '商品記事v2担当（アズ）'), ('followup', '修正対応・リライト後続処理（なお姉）'), ('qa', '検品担当（リン様）')], max_length=16, verbose_name='担当'),
        ),
    ]
