# Generated by Django 5.2.13 on 2026-09-08 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0020_alter_editornote_assignee'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleWorkLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('rewrite', 'リライト案'), ('article', '新規記事'), ('product_v2', '商品記事v2')], db_index=True, max_length=12, verbose_name='対象')),
                ('target_id', models.IntegerField(db_index=True, verbose_name='対象ID')),
                ('slug', models.CharField(blank=True, max_length=500, verbose_name='スラッグ')),
                ('agent', models.CharField(choices=[('desk', '編集長（レイカさん）'), ('researcher', 'リサーチ担当（しおりん）'), ('writer', '新規執筆担当（ふみちゃん）'), ('product_writer', '商品記事v2担当（アズ）'), ('qa', '検品担当（リン様）'), ('followup', '修正対応・リライト後続（なお姉）'), ('observe', '観測cron（ミオ）'), ('human', '運営（人）')], max_length=16, verbose_name='担当')),
                ('action', models.CharField(choices=[('researched', 'リサーチ'), ('written', '執筆'), ('queued', '承認キューに投入'), ('revised', '修正対応'), ('qa_passed', '検品 合格(無修正)'), ('qa_fixed', '検品 合格(調整あり)'), ('qa_failed', '検品 要差戻し'), ('note_added', '人が修正指示を記入'), ('sent_back', '人が差し戻し'), ('applied', '本番へ反映・公開'), ('other', 'その他')], max_length=16, verbose_name='作業')),
                ('summary', models.CharField(max_length=300, verbose_name='何をしたか(1行)')),
                ('detail', models.TextField(blank=True, verbose_name='詳細')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='記録日時')),
            ],
            options={
                'verbose_name': '記事の作業履歴',
                'verbose_name_plural': '記事の作業履歴',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['kind', 'target_id', 'created_at'], name='analytics_a_kind_a8ab62_idx')],
            },
        ),
    ]
