# Generated by Django 5.2.13 on 2026-09-09 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0021_articleworklog'),
    ]

    operations = [
        migrations.AddField(
            model_name='editornote',
            name='source',
            field=models.CharField(choices=[('human', '運営（人）'), ('qa', '検品担当（リン様）')], db_index=True, default='human', max_length=8, verbose_name='出どころ'),
        ),
    ]
