# Generated by Django 5.2.13 on 2026-09-13 23:16

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0022_editornote_source'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeskDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(db_index=True, max_length=200, verbose_name='論点キー')),
                ('category', models.CharField(choices=[('discontinued', '生産終了・商品データ'), ('cannibal', 'カニバリ・統合'), ('revenue', '収益・成約'), ('seo', 'タイトル・SEO'), ('quality', '品質・検品'), ('policy', '方針・戦略'), ('other', 'その他')], db_index=True, default='other', max_length=16, verbose_name='種類')),
                ('title', models.CharField(max_length=200, verbose_name='判断してほしいこと')),
                ('background', models.TextField(blank=True, help_text='Markdown可', verbose_name='背景・根拠')),
                ('recommendation', models.TextField(blank=True, verbose_name='編集長の推奨案')),
                ('options', models.JSONField(blank=True, default=list, verbose_name='選択肢')),
                ('slugs', models.CharField(blank=True, max_length=500, verbose_name='関係するslug')),
                ('status', models.CharField(choices=[('open', '回答待ち'), ('answered', '回答済み・編集長が反映中'), ('dev_pending', '開発作業待ち'), ('done', '完了'), ('withdrawn', '取り下げ')], db_index=True, default='open', max_length=12, verbose_name='状態')),
                ('times_raised', models.PositiveIntegerField(default=1, verbose_name='提起回数')),
                ('first_raised_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='初回提起')),
                ('last_raised_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='最終提起')),
                ('choice', models.CharField(blank=True, max_length=40, verbose_name='選んだ選択肢')),
                ('choice_label', models.CharField(blank=True, max_length=200, verbose_name='選んだ選択肢(表示名)')),
                ('answer_comment', models.TextField(blank=True, verbose_name='回答コメント')),
                ('answered_by', models.CharField(blank=True, max_length=150, verbose_name='回答者')),
                ('answered_at', models.DateTimeField(blank=True, null=True, verbose_name='回答日時')),
                ('action_result', models.TextField(blank=True, verbose_name='回答時に実行した処理')),
                ('handled_note', models.TextField(blank=True, verbose_name='編集長の反映内容')),
                ('handled_at', models.DateTimeField(blank=True, null=True, verbose_name='反映日時')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成')),
                ('source_report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decisions', to='analytics.workreport', verbose_name='出典の報告')),
            ],
            options={
                'verbose_name': '編集長からの判断待ち',
                'verbose_name_plural': '編集長からの判断待ち',
                'ordering': ['-last_raised_at'],
            },
        ),
    ]
