# Generated by Django 5.2.13 on 2026-09-13 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0023_deskdecision'),
    ]

    operations = [
        migrations.CreateModel(
            name='OutboundClick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='クリック日時')),
                ('network', models.CharField(choices=[('rakuten', '楽天'), ('amazon', 'Amazon'), ('other', 'その他')], db_index=True, max_length=10, verbose_name='リンク先')),
                ('page', models.CharField(db_index=True, max_length=500, verbose_name='押されたページ')),
                ('href', models.URLField(max_length=1000, verbose_name='リンクURL')),
                ('product_slug', models.CharField(blank=True, db_index=True, help_text='リンクURLが商品のaffiliate/rakuten/amazon URLと一致した場合', max_length=255, verbose_name='商品slug')),
                ('link_text', models.CharField(blank=True, max_length=120, verbose_name='ボタン文言')),
                ('section', models.CharField(blank=True, max_length=200, verbose_name='直前の見出し')),
                ('container', models.CharField(blank=True, max_length=200, verbose_name='置き場所（周囲のclass）')),
                ('device', models.CharField(blank=True, max_length=10, verbose_name='端末')),
                ('referrer', models.CharField(blank=True, max_length=300, verbose_name='流入元')),
                ('ip_hash', models.CharField(blank=True, db_index=True, max_length=16, verbose_name='IPハッシュ')),
                ('user_agent', models.CharField(blank=True, max_length=300, verbose_name='UA')),
                ('is_bot', models.BooleanField(db_index=True, default=False, verbose_name='Bot判定')),
                ('is_staff', models.BooleanField(db_index=True, default=False, verbose_name='運営のクリック')),
            ],
            options={
                'verbose_name': '購入リンクのクリック',
                'verbose_name_plural': '購入リンクのクリック',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['network', 'created_at'], name='analytics_o_network_3c85c7_idx')],
            },
        ),
    ]
