# Generated by Django 5.2.13 on 2026-04-23 13:40

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("products", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rating",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                        verbose_name="星評価",
                    ),
                ),
                ("title", models.CharField(max_length=120, verbose_name="タイトル")),
                ("body", models.TextField(verbose_name="本文")),
                (
                    "usage_period",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("lt1m", "1ヶ月未満"),
                            ("1-3m", "1〜3ヶ月"),
                            ("3-6m", "3〜6ヶ月"),
                            ("6-12m", "6ヶ月〜1年"),
                            ("gt1y", "1年以上"),
                        ],
                        max_length=8,
                        verbose_name="使用期間",
                    ),
                ),
                (
                    "effectiveness",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("excellent", "とても効果を感じた"),
                            ("good", "効果を感じた"),
                            ("neutral", "どちらとも言えない"),
                            ("poor", "あまり感じなかった"),
                            ("none", "効果を感じなかった"),
                        ],
                        max_length=16,
                        verbose_name="効果実感",
                    ),
                ),
                (
                    "skin_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("dry", "乾燥肌"),
                            ("oily", "脂性肌"),
                            ("combination", "混合肌"),
                            ("sensitive", "敏感肌"),
                            ("normal", "普通肌"),
                        ],
                        max_length=16,
                        verbose_name="投稿時の肌質",
                    ),
                ),
                (
                    "is_approved",
                    models.BooleanField(
                        default=True,
                        help_text="管理者が非表示にする場合はチェックを外してください",
                        verbose_name="承認済み",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="products.product",
                        verbose_name="美顔器",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="投稿者",
                    ),
                ),
            ],
            options={
                "verbose_name": "口コミ",
                "verbose_name_plural": "口コミ",
                "ordering": ["-created_at"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("product", "user"),
                        name="unique_review_per_product_user",
                    )
                ],
            },
        ),
    ]
