# Generated by Django 5.2.13 on 2026-04-25 18:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='control',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='操作性'),
        ),
        migrations.AddField(
            model_name='review',
            name='cospa',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='コスパ'),
        ),
        migrations.AddField(
            model_name='review',
            name='expression',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='表情'),
        ),
        migrations.AddField(
            model_name='review',
            name='icon',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='アイコン番号'),
        ),
        migrations.AddField(
            model_name='review',
            name='safety',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='安全性'),
        ),
        migrations.AddField(
            model_name='review',
            name='wp_comment_id',
            field=models.IntegerField(blank=True, help_text='WordPressからの取り込み元ID（冪等インポート用）', null=True, unique=True, verbose_name='WPコメントID'),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='総合評価'),
        ),
    ]
