# Generated by Django 5.2.13 on 2026-04-25 21:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_review_control_review_cospa_review_expression_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='is_approved',
            field=models.BooleanField(default=True, verbose_name='承認済み'),
        ),
        migrations.AlterField(
            model_name='review',
            name='wp_comment_id',
            field=models.IntegerField(blank=True, help_text='WordPressからの取り込み元ID', null=True, unique=True, verbose_name='WPコメントID'),
        ),
        migrations.CreateModel(
            name='ReviewHelpful',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='helpfuls', to='reviews.review', verbose_name='口コミ')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_helpfuls', to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
            ],
            options={
                'verbose_name': '参考になった',
                'verbose_name_plural': '参考になった',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'review')},
            },
        ),
    ]
