# Generated by Django 5.2.13 on 2026-06-13 08:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_alter_review_is_approved_alter_review_wp_comment_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='reviews/%Y/%m/', verbose_name='画像')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='表示順')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='reviews.review', verbose_name='口コミ')),
            ],
            options={
                'verbose_name': '口コミ画像',
                'verbose_name_plural': '口コミ画像',
                'ordering': ['order', 'id'],
            },
        ),
    ]
