# Generated by Django 5.2.13 on 2026-06-22 07:43

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_reviewimage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('inappropriate', '不適切な内容'), ('false_info', '虚偽・誇張された内容'), ('harassment', '誹謗中傷・嫌がらせ'), ('personal_info', '個人情報が含まれている'), ('rights_violation', '著作権・肖像権などの権利侵害'), ('stealth_marketing', '広告・ステマの疑い'), ('unrelated', '商品と関係がない'), ('other', 'その他')], max_length=32, verbose_name='通報理由')),
                ('comment', models.TextField(blank=True, help_text='任意。最大1000文字。', validators=[django.core.validators.MaxLengthValidator(1000)], verbose_name='詳細コメント')),
                ('status', models.CharField(choices=[('pending', '未対応'), ('reviewing', '確認中'), ('resolved', '対応済み'), ('rejected', '却下')], default='pending', max_length=16, verbose_name='対応ステータス')),
                ('admin_note', models.TextField(blank=True, verbose_name='運営メモ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='対応日時')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_reports', to=settings.AUTH_USER_MODEL, verbose_name='通報者')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_review_reports', to=settings.AUTH_USER_MODEL, verbose_name='対応した管理者')),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='reviews.review', verbose_name='対象口コミ')),
            ],
            options={
                'verbose_name': '口コミ通報',
                'verbose_name_plural': '口コミ通報',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('review', 'reporter'), name='unique_report_per_review_reporter')],
            },
        ),
    ]
