# Generated by Django 5.2.13 on 2026-06-23 21:24

import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0005_reviewreport'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'base_manager_name': 'all_objects', 'ordering': ['-created_at'], 'verbose_name': '口コミ', 'verbose_name_plural': '口コミ'},
        ),
        migrations.AlterModelManagers(
            name='review',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='review',
            name='campaign_consumed_at',
            field=models.DateTimeField(blank=True, help_text='達成したキャンペーンの集計に算入された日時。以後は別キャンペーンの集計対象にせず、会員からの削除も不可にする。', null=True, verbose_name='キャンペーン算入日時'),
        ),
        migrations.AddField(
            model_name='review',
            name='delete_count',
            field=models.PositiveSmallIntegerField(default=0, help_text='この口コミが削除→再投稿された回数。0より大きいと再投稿の常習を確認できる。', verbose_name='削除回数'),
        ),
        migrations.AddField(
            model_name='review',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='削除日時'),
        ),
        migrations.AddField(
            model_name='review',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, help_text='会員が削除した口コミ。サイト表示・集計からは除外し、運営のみ閲覧可。', verbose_name='削除済み'),
        ),
    ]
