# Generated by Django 5.2.13 on 2026-06-23 21:46

import django.core.validators
import django.db.models.deletion
import django.db.models.manager
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0025_seed_brands'),
        ('reviews', '0006_alter_review_options_alter_review_managers_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductUseLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(validators=[django.core.validators.MaxLengthValidator(5000)], verbose_name='本文')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='投稿者が削除した使用記録。表示からは除外し、運営のみ閲覧可。', verbose_name='削除済み')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='削除日時')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='use_logs', to='products.product', verbose_name='商品')),
                ('review', models.ForeignKey(blank=True, help_text='任意。同じ商品・同じ投稿者の通常口コミにのみ紐付けられる。', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='use_logs', to='reviews.review', verbose_name='紐付け口コミ')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='use_logs', to=settings.AUTH_USER_MODEL, verbose_name='投稿者')),
            ],
            options={
                'verbose_name': '使用記録',
                'verbose_name_plural': '使用記録',
                'ordering': ['-created_at'],
                'base_manager_name': 'all_objects',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='ProductUseLogImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='use_logs/%Y/%m/', verbose_name='画像')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='表示順')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('use_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='reviews.productuselog', verbose_name='使用記録')),
            ],
            options={
                'verbose_name': '使用記録画像',
                'verbose_name_plural': '使用記録画像',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ProductUseLogReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('inappropriate', '不適切な内容'), ('false_info', '虚偽・誇張された内容'), ('harassment', '誹謗中傷・嫌がらせ'), ('personal_info', '個人情報が含まれている'), ('rights_violation', '著作権・肖像権などの権利侵害'), ('stealth_marketing', '広告・ステマの疑い'), ('unrelated', '商品と関係がない'), ('other', 'その他')], max_length=32, verbose_name='通報理由')),
                ('comment', models.TextField(blank=True, help_text='任意。最大1000文字。', validators=[django.core.validators.MaxLengthValidator(1000)], verbose_name='詳細コメント')),
                ('status', models.CharField(choices=[('pending', '未対応'), ('reviewing', '確認中'), ('resolved', '対応済み'), ('rejected', '却下')], default='pending', max_length=16, verbose_name='対応ステータス')),
                ('admin_note', models.TextField(blank=True, verbose_name='運営メモ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='対応日時')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='use_log_reports', to=settings.AUTH_USER_MODEL, verbose_name='通報者')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_use_log_reports', to=settings.AUTH_USER_MODEL, verbose_name='対応した管理者')),
                ('use_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='reviews.productuselog', verbose_name='対象使用記録')),
            ],
            options={
                'verbose_name': '使用記録通報',
                'verbose_name_plural': '使用記録通報',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('use_log', 'reporter'), name='unique_report_per_uselog_reporter')],
            },
        ),
    ]
