# Generated by Django 5.2.13 on 2026-06-23 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0007_productuselog_productuselogimage_productuselogreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='productuselog',
            name='title',
            field=models.CharField(blank=True, help_text='任意。一覧で見出しとして表示する。', max_length=120, verbose_name='タイトル'),
        ),
    ]
