# Generated by Django 5.2.13 on 2026-07-29 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0008_productuselog_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='is_approved',
            field=models.BooleanField(default=False, help_text='新規投稿は承認待ち(False)で作成し、運営が内容確認後に承認して掲載する。', verbose_name='承認済み'),
        ),
    ]
