# Generated by Django 5.2.13 on 2026-07-30 02:00

from django.db import migrations, models


def approve_existing(apps, schema_editor):
    # 承認制導入前に投稿された使用記録は既に公開されていたため承認済み扱いにする
    # （遡って非表示にしない）。
    ProductUseLog = apps.get_model("reviews", "ProductUseLog")
    ProductUseLog.objects.update(is_approved=True)


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0009_alter_review_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='productuselog',
            name='is_approved',
            field=models.BooleanField(db_index=True, default=False, help_text='承認すると商品ページ・APIに掲載されます。未承認は投稿者本人と運営のみ閲覧可（本人には「承認待ち」と表示）。', verbose_name='承認済み'),
        ),
        migrations.RunPython(approve_existing, migrations.RunPython.noop),
    ]
