# Generated by Django 5.2.13 on 2026-09-06 06:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0010_productuselog_is_approved'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='guest_name',
            field=models.CharField(blank=True, default='', help_text='非会員投稿の表示名。空なら「匿名」表示', max_length=40, verbose_name='ゲスト表示名'),
        ),
        migrations.AddField(
            model_name='review',
            name='ip_hash',
            field=models.CharField(blank=True, db_index=True, default='', help_text='非会員投稿のレート制限用(SHA-256・生IPは保存しない)', max_length=64, verbose_name='投稿元IPハッシュ'),
        ),
        migrations.AlterField(
            model_name='review',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL, verbose_name='投稿者'),
        ),
    ]
