# Generated by Django 5.2.13 on 2026-09-06 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0011_review_guest_name_review_ip_hash_alter_review_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='is_rejected',
            field=models.BooleanField(db_index=True, default=False, help_text='運営判断で掲載しない口コミ(薬機法等)。承認センターの承認待ちから外れる。削除とは別で、ここを外せば承認待ちに戻る。', verbose_name='非承認(掲載しない)'),
        ),
    ]
